material_iron = 'iron'
material_titanium = 'titanium'
material_naonite = 'naonite'
material_trinium = 'trinium'
material_xanion = 'xanion'
material_ogonite = 'ogonite'
material_avorion = 'avorion'

block_armor = 'armor'
block_engine = 'engine'
block_cargo = 'cargo'
block_quarters = 'quarters'
block_thruster = 'thruster'
block_hangar = 'hangar'
block_shield = 'shield'
block_energy_container = 'energy_container'
block_generator = 'generator'
block_integrity = 'integrity'
block_computer = 'computer'
block_gyro = 'gyro'
block_dampener = 'dampener'

attribute_energy_consumption = 'energy_consumption'
attribute_credits = 'credits'
attribute_energy_storage = 'energy_storage'
attribute_hp = 'hp'
attribute_shield = 'shield'
attribute_processing = 'processing'
attribute_mass = 'mass'
attribute_cost = 'cost'
attribute_crew = 'crew'
attribute_hangar = 'hangar'
attribute_energy_generation = 'energy_generation'
attribute_dampener_force = 'dampener_force'


# attribute_yaw = 'yaw'
# attribute_pitch = 'pitch'
# attribute_roll = 'roll'

def calculate_hyperspace_jump_energy(volume: float, mass: float):
    return volume * mass
